# Generated by Django 2.2.19 on 2021-11-08 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя ингредиента')),
                ('unit', models.CharField(max_length=50, verbose_name='Ед. измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Имя тега')),
                ('color', models.CharField(choices=[('#FF0000', 'Красный'), ('#006400', 'Зеленый'), ('#0000FF', 'Синий'), ('#A52A2A', 'Коричневый'), ('#800080', 'Фиолетовый')], max_length=30, unique=True, verbose_name='HEX-цвет')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Слаг')),
            ],
        ),
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя рецепта')),
                ('image', models.ImageField(upload_to='images', verbose_name='Картинка')),
                ('text', models.CharField(max_length=500, verbose_name='Описание')),
                ('time', models.PositiveSmallIntegerField(verbose_name='Время готовки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recept', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта')),
                ('ingredients', models.ManyToManyField(to='api.Ingredient', verbose_name='Ингредиенты')),
                ('tags', models.ManyToManyField(to='api.Tag', verbose_name='Теги')),
            ],
        ),
    ]
