# Generated by Django 2.2.6 on 2021-11-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211112_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recept',
            old_name='time',
            new_name='cooking_time',
        ),
    ]
