# Generated by Django 2.2.6 on 2021-11-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211112_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientamount',
            old_name='recept',
            new_name='recipe',
        ),
    ]
